### ISSUE TITLE
[PHP] haxe.Template fails

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#10085]
Hej !

This sample https://haxe.org/manual/std-template.html fails in PHP 7 with Haxe Compiler 4.2.0-rc.1+5145ddb
Error : 
```haxe
Fatal error:  Uncaught Macro call display(<function>,{ name : Mark, distance : 3500 },15) failed (ErrorException: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /lib/Reflect.php:37
Stack trace:
#0 /lib/Reflect.php(37): php\Boot::php\{closure}(2, 'call_user_func_...', '/srv/www/bgds/o...', 37, Array)
#1 /lib/haxe/Template.php(916): Reflect::callMethod(Object(Server), NULL, Object(Array_hx))
#2 /lib/haxe/Template.php(826): haxe\Template-&gt;run(Object(haxe\_Template\TemplateExpr))
#3 /lib/haxe/Template.php(127): haxe\Template-&gt;run(Object(haxe\_Template\TemplateExpr))
#4 /lib/Server.php(163): haxe\Template-&gt;execute(Object(_HxAnon_Server4), Object(Server))
#5 /lib/Server.php(42): Server-&gt;__construct()
#6 /srv/www/bgds/office/www/index.php(14): Server::main()
#7 {main})
  thrown in /lib/haxe/Exception.php on line 96
```

**Comment by filt3rek** [comment]
I think something is going wrong in `Reflect.field`, it gives `null`

**Comment by RealyUniqueName** [comment]
That sample fails on all targets and with all Haxe versions I tested.

**Comment by RealyUniqueName** [comment]
Actually the sample works fine with dce disabled. Which is default compilation setting.
I think DCE should be mentioned somewhere in the article about `haxe.Template` since it is reflection-based.
