### ISSUE TITLE
enum/class named `Attribute` will fail at runtime with PHP 8

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#10207]
```haxe
enum Attribute { // rename Attribute to anything to workaround
	A;
}

class Test {
	static function main() {
		trace(A);
	}
}
```

Runtime error with PHP 8.0.3
```
Fatal error: Uncaught Error: Call to undefined method Attribute::A() in /Users/andy/Documents/workspace/ansi/bin/php/lib/Test.php:16
Stack trace:
#0 /Users/andy/Documents/workspace/ansi/bin/php/index.php(13): Test::main()
#1 {main}
  thrown in /Users/andy/Documents/workspace/ansi/bin/php/lib/Test.php on line 16

PHP Fatal error:  Uncaught Error: Call to undefined method Attribute::A() in /Users/andy/Documents/workspace/ansi/bin/php/lib/Test.php:16
Stack trace:
#0 /Users/andy/Documents/workspace/ansi/bin/php/index.php(13): Test::main()
#1 {main}
  thrown in /Users/andy/Documents/workspace/ansi/bin/php/lib/Test.php on line 16
Error: Command failed with error 255
```

Note that it runs fine with PHP 7.4.

**Comment by RealyUniqueName** [comment]
Class `Attribute` was introduced in the standard library of PHP8. And it shadows user-defined classes with the same name.
We need externs for all PHP classes in our std lib. And then php generator could check if there are collisions between Haxe-generated types and native classes of PHP.
