### ISSUE TITLE
[jvm] JNI error when inlining functions

### ISSUE THREAD

**Issue by leonaci** [HaxeFoundation/haxe#10439]
I encountered weird errors when inlining functions.
One happens for
```haxe
class Test
{
	static function main()
	{
		var b = false;
		if (b) inlineFunc();
	}
	
	static macro function inlineFunc() {
		var num = 1311;
		return macro $b{[for (_ in 0...num) macro func()]};
	}
	
	static inline function func():Void
	{
		trace(0);
	}
}
```
and the error is
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target -32755
Exception Details:
  Location:
    haxe/root/Test.main()V @3: ifeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 033b 1a99 800a b200 13c0 0015 03bb 0017
    ...
    0x0008000: 1912 1b10 1212 1db7 0021 b600 25b1
  Stackmap Table:
    append_frame(@6,Integer)
    same_frame_extended(@32781)

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```
The bytecode is too long and I skipped.

The other happens for
```haxe
class Test
{
	static function main()
	{
		inlineFunc();
	}
	
	static macro function inlineFunc() {
		var num = 2622;
		return macro $b{[for (_ in 0...num) macro func()]};
	}
	
	static inline function func():Void
	{
		trace(0);
	}
}
```
and the error is
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.ClassFormatError: Invalid method Code length 65551 in class file haxe/root/Test
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```

The `num` changes if the content of the `func` or the way of inlining changes and I feel like the more complicated the situation gets, the smaller the `num` gets.
If the `num` is so big, `IO.Overflow("write_ui16")` happens on compiling(#9654).
Originally, I got the first error on a complex (but ordinary) situation. But it is difficult to make a minimal repro case and after a lot of fiddling around to make it I encountered the second.
Maybe it is related to #10213.

Thanks.

**Comment by Simn** [comment]
This has always confused me. The `Code` attribute clearly allows 32bit:

```
    u4 code_length;
    u1 code[code_length];
```

However, all the delta offsets in the `StackMapTable` are 16bit:

```
    u2 offset_delta;
```

Also, the conditionals use 16bit branch offsets:

```
if<cond>
branchbyte1
branchbyte2
```

So this may just be a JVM limitation. I wonder what real Java compilers do with huge functions like this...

**Comment by Simn** [comment]
I don't think this is a bug on our end, about the only thing we could do here is improve the error message.

**Comment by Simn** [comment]
I'll go ahead and close this because I don't see the point in replicating all the related error messages from Java, which are likely going to be more accurate anyway.
