### ISSUE TITLE
Module-level field init hover doesn't work on first try

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe#10638]
```haxe
var x = "foo";

class Main {
	static function main() {}
}
```

Hovering the `"foo"` for the first time doesn't show any result. The second time it works as expected. I'm not sure yet what the scope of this is.

**Comment by Simn** [comment]
The first problem here is that a position-based lookup fails because the implicit module for module-level fields has a 0-0 position.

However, there must be something else going on because the file is supposed to be invalidated if this lookup fails, which _should_ just trigger normal processing. I think what happens here is that the compiler taints the module in the cache, but at this point it is already part of the common context because we typed it. This would require a slightly different approach, while also keeping #8991 in mind.

**Comment by Simn** [comment]
Come to think of it, we should test that everything still works without the display-texpr optimization, because it's supposed to be just that, an optimization. If I comment it out, I'm getting some test failures from the server tests:

```
results: SOME TESTS FAILURES (success: false)
cases.ServerTests
cases.display.issues.Issue9012
  test: FAILURE F
    line: 13, Exception: Cannot read properties of null (reading 'item')
Called from module TypeError: Cannot read properties of null (reading 'item')
Called from module at C:\git\haxe\tests\server\test.js:3648:66
Called from haxeserver_process__$HaxeServerProcessNode_RequestCallback.callback (C:\git\haxe\tests\server\test.js line 65 column 4)
Called from haxeserver_process_HaxeServerProcessNode.processBuffer (C:\git\haxe\tests\server\test.js line 6217 column 18)
Called from haxeserver_process_HaxeServerProcessNode.handleOnStderr (C:\git\haxe\tests\server\test.js line 6177 column 8)
Called from Socket.emit (node:events line 526 column 28)
Called from .addChunk (node:internal/streams/readable line 315 column 12)
Called from .readableAddChunk (node:internal/streams/readable line 289 column 9)
Called from Socket.Readable.push (node:internal/streams/readable line 228 column 10)
Called from Pipe.onStreamRead (node:internal/stream_base_commons line 190 column 23)
cases.display.issues.Issue9044
  test: FAILURE .F
    line: 53, expected 3 elements but they are 0
cases.display.issues.Issue9115
  test: FAILURE F
    line: 13, Exception: Cannot read properties of null (reading 'item')
Called from module TypeError: Cannot read properties of null (reading 'item')
Called from module at C:\git\haxe\tests\server\test.js:4037:57
Called from haxeserver_process__$HaxeServerProcessNode_RequestCallback.callback (C:\git\haxe\tests\server\test.js line 65 column 4)
Called from haxeserver_process_HaxeServerProcessNode.processBuffer (C:\git\haxe\tests\server\test.js line 6217 column 18)
Called from haxeserver_process_HaxeServerProcessNode.handleOnStderr (C:\git\haxe\tests\server\test.js line 6177 column 8)
Called from Socket.emit (node:events line 526 column 28)
Called from .addChunk (node:internal/streams/readable line 315 column 12)
Called from .readableAddChunk (node:internal/streams/readable line 289 column 9)
Called from Socket.Readable.push (node:internal/streams/readable line 228 column 10)
Called from Pipe.onStreamRead (node:internal/stream_base_commons line 190 column 23)
cases.display.issues.Issue9790
  test: FAILURE F
    line: 24, Exception: Cannot read properties of null (reading 'range')
Called from module TypeError: Cannot read properties of null (reading 'range')
Called from module at C:\git\haxe\tests\server\test.js:4521:57
Called from haxeserver_process__$HaxeServerProcessNode_RequestCallback.callback (C:\git\haxe\tests\server\test.js line 65 column 4)
Called from haxeserver_process_HaxeServerProcessNode.processBuffer (C:\git\haxe\tests\server\test.js line 6217 column 18)
Called from haxeserver_process_HaxeServerProcessNode.handleOnStderr (C:\git\haxe\tests\server\test.js line 6177 column 8)
Called from Socket.emit (node:events line 526 column 28)
Called from .addChunk (node:internal/streams/readable line 315 column 12)
Called from .readableAddChunk (node:internal/streams/readable line 289 column 9)
Called from Socket.Readable.push (node:internal/streams/readable line 228 column 10)
Called from Pipe.onStreamRead (node:internal/stream_base_commons line 190 column 23)
cases.display.issues.Issue9824
  test: FAILURE F
    line: 21, Exception: Cannot read properties of null (reading 'expected')
Called from module TypeError: Cannot read properties of null (reading 'expected')
Called from module at C:\git\haxe\tests\server\test.js:4573:58
Called from haxeserver_process__$HaxeServerProcessNode_RequestCallback.callback (C:\git\haxe\tests\server\test.js line 65 column 4)
Called from haxeserver_process_HaxeServerProcessNode.processBuffer (C:\git\haxe\tests\server\test.js line 6217 column 18)
Called from haxeserver_process_HaxeServerProcessNode.handleOnStderr (C:\git\haxe\tests\server\test.js line 6177 column 8)
Called from Socket.emit (node:events line 526 column 28)
Called from .addChunk (node:internal/streams/readable line 315 column 12)
Called from .readableAddChunk (node:internal/streams/readable line 289 column 9)
Called from Socket.Readable.push (node:internal/streams/readable line 228 column 10)
Called from Pipe.onStreamRead (node:internal/stream_base_commons line 190 column 23)
```

What's even more concerning is that I'm also getting failures from the normal display tests, which aren't supposed to be affected by this at all:

```
assertations: 1191
successes: 1166
errors: 7
failures: 18
warnings: 0
execution time: 19.109

results: SOME TESTS FAILURES (success: false)
cases.InMacro
  testMacro1: ERROR ..E
    HaxeInvocationException(Error: No completion point was found

, testMacro1, [--display,src/cases/InMacro.hx@190@position], package cases;


                import haxe.macro.Context;

                class Main {

                        #if macro

                        static function buildTypeDef( t : haxe.macro.Type ) : Expr {
                                Context.error("Unsupported type "+Std.string(t),Context.currentPos());
                                return null;
                        }

                        #else

                        static function buildTypeDef( t : haxe.macro.Type) : Expr {
                                trace("not a macro" + t);
                                return null;
                        }

                        #end
                }
        ])
Called from local function #1 (src/cases/InMacro.hx line 27 column 2)
Called from cases.InMacro.testMacro1 (src/cases/InMacro.hx line 30 column 19)
Called from DisplayTestContext.position (src/DisplayTestContext.hx line 72 column 10)
Called from DisplayTestContext.positions (src/DisplayTestContext.hx line 68 column 27)
Called from DisplayTestContext.callHaxe (src/DisplayTestContext.hx line 113 column 4)
cases.Basic
  testCtorClosureType: ERROR E
    HaxeInvocationException(Error: No completion point was found

, testCtorClosureType, [--display,src/cases/Basic.hx@97@type], package cases;

                class Some {
                        function new(someName:Int) {}
                        function main() {
                                Some.new
                        }
                }
        ])
Called from local function #9 (src/cases/Basic.hx line 113 column 2)
Called from cases.Basic.testCtorClosureType (src/cases/Basic.hx line 114 column 40)
Called from DisplayTestContext.type (src/DisplayTestContext.hx line 64 column 22)
Called from DisplayTestContext.callHaxe (src/DisplayTestContext.hx line 113 column 4)
  testFieldDisplay: ERROR E
    HaxeInvocationException(Error: No completion point was found

, testFieldDisplay, [--display,src/cases/Basic.hx@46@type], package cases;

                class Some {
                        var x1 = "fo";
                        static var x2 = "fo";
                        static inline var x3 = "fo";

                        var x4(default, null) = "fo";
                        static var x5(default, null) = "fo";

                        static var x6:String;
                }
        ])
Called from local function #8 (src/cases/Basic.hx line 89 column 2)
Called from cases.Basic.testFieldDisplay (src/cases/Basic.hx line 90 column 16)
Called from DisplayTestContext.type (src/DisplayTestContext.hx line 64 column 22)
Called from DisplayTestContext.callHaxe (src/DisplayTestContext.hx line 113 column 4)
  testLocalFunction: ERROR E
    HaxeInvocationException(Error: No completion point was found

, testLocalFunction, [--display,src/cases/Basic.hx@72@type], package cases;
class Main { static function main() {
                function test(name:String) { }
        }}])
Called from local function #7 (src/cases/Basic.hx line 72 column 13)
Called from cases.Basic.testLocalFunction (src/cases/Basic.hx line 73 column 16)
Called from DisplayTestContext.type (src/DisplayTestContext.hx line 64 column 22)
Called from DisplayTestContext.callHaxe (src/DisplayTestContext.hx line 113 column 4)
  testMissingParams: ERROR E
    HaxeInvocationException(Error: No completion point was found

, testMissingParams, [--display,src/cases/Basic.hx@64@type], package cases;
class Main { static function main() {
                var a:Array;
        }}])
Called from local function #6 (src/cases/Basic.hx line 101 column 13)
Called from cases.Basic.testMissingParams (src/cases/Basic.hx line 102 column 24)
Called from DisplayTestContext.type (src/DisplayTestContext.hx line 64 column 22)
Called from DisplayTestContext.callHaxe (src/DisplayTestContext.hx line 113 column 4)
  testPosition1: ERROR E
    HaxeInvocationException(Error: No completion point was found

, testPosition1, [--display,src/cases/Basic.hx@78@position], package cases;

                class Some {
                        function main() {
                                var variable = 5;
                                variable;
                        }
                }
        ])
Called from local function #5 (src/cases/Basic.hx line 24 column 2)
Called from cases.Basic.testPosition1 (src/cases/Basic.hx line 25 column 19)
Called from DisplayTestContext.position (src/DisplayTestContext.hx line 72 column 10)
Called from DisplayTestContext.positions (src/DisplayTestContext.hx line 68 column 27)
Called from DisplayTestContext.callHaxe (src/DisplayTestContext.hx line 113 column 4)
  testType1: ERROR E
    HaxeInvocationException(Error: No completion point was found

, testType1, [--display,src/cases/Basic.hx@72@type], package cases;

                class Some {
                        function main() {
                                var a = 5;
                                a
                        }
                }
        ])
Called from local function #4 (src/cases/Basic.hx line 12 column 2)
Called from cases.Basic.testType1 (src/cases/Basic.hx line 13 column 13)
Called from DisplayTestContext.type (src/DisplayTestContext.hx line 64 column 22)
Called from DisplayTestContext.callHaxe (src/DisplayTestContext.hx line 113 column 4)
  testUsage1: FAILURE F
    line: 39, expected "C:\git\haxe\tests\display\src\cases\Basic.hx:6: characters 5-13" but it is null
cases.TypeHints
  testTypedef1: FAILURE ...F
    line: 13, expected 1 elements but they are 0
  testClass1: FAILURE FF
    line: 71, expected 1 elements but they are 0
    line: 72, expected 1 elements but they are 0
  testInterface1: FAILURE FF
    line: 80, expected 1 elements but they are 0
    line: 81, expected 1 elements but they are 0
  testStructure1: FAILURE FF
    line: 25, expected 2 elements but they are 0
    line: 26, expected 2 elements but they are 0
  testEnum1: FAILURE FFF
    line: 38, expected 2 elements but they are 0
    line: 39, expected 2 elements but they are 0
    line: 40, expected 2 elements but they are 0
  testFunction1: FAILURE FFF
    line: 61, expected 2 elements but they are 0
    line: 62, expected 2 elements but they are 0
    line: 63, expected 2 elements but they are 0
  testAbstract1: FAILURE FFFF
    line: 49, expected 3 elements but they are 0
    line: 50, expected 3 elements but they are 0
    line: 51, expected 3 elements but they are 0
    line: 52, expected 3 elements but they are 0
```

Most of the latter are recent regressions from my frontend changes, but it's very likely that we're mostly exposing already existing symptoms now. This suspicion is strengthened by the fact that most of the failing server tests are not recent regressions.

**Comment by Simn** [comment]
Disregard everything I've said and call me an idiot. The reason everything was failing was because I commented out the optimization in a away that also disabled the code which invalidates the display file in the first place. This meant that the server would always happily grab the intact display file from the cache and never actually do anything with it.

There are only two server test failures now, and both of those depend on the optimization by testing that the display file is being reused during display requests, which only makes sense if we grab it from the cache.
