### ISSUE TITLE
Vector.fromArrayCopy does not work in a method that has type parameters if not inline

### ISSUE THREAD

**Issue by Atry** [HaxeFoundation/haxe#3399]
``` haxe
import haxe.ds.Vector;

class FromArrayCopy
{
    static function notInline<T>(a:Array<T>) return Vector.fromArrayCopy(a);

    public static function main()
    {
        var v:Vector<String> = notInline([""]);
    }
}
```

```
$ haxe -java java -main FromArrayCopy
haxelib run hxjava hxjava_build.txt --haxe-version 3200
D:\Program Files (x86)\Java\jdk1.7.0_55/bin/javac.exe "-sourcepath" "src" "-d" "obj" "-g:none" "@cmd"
```

```
$ java -jar java/FromArrayCopy.jar
Exception in thread "main" java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
        at haxe.root.FromArrayCopy.main(Unknown Source)
        at haxe.root.FromArrayCopy.main(Unknown Source)
```

```
$ haxe -cs cs -main FromArrayCopy
haxelib run hxcs hxcs_build.txt --haxe-version 3200
```

```
$ cs/bin/FromArrayCopy.exe

未经处理的异常:  System.InvalidCastException: 无法将类型为“System.Object[]”的对象强制转换为类型“System.String[]”。
   在 FromArrayCopy.main()
   在 FromArrayCopy.Main()
```

**Comment by Simn** [comment]
This is also the same as #3398.
