### ISSUE TITLE
ease inlining condition

### ISSUE THREAD

**Issue by mandel59** [HaxeFoundation/haxe#4353]
I wonder `Iter.next` in Inlining2 could be inlined as `Iter.next` in Inlining3 is.

This issue affects inline constructor optimization on https://github.com/mandel59/unifill/blob/master/unifill/InternalEncodingIter.hx

```haxe
// Inlining2.hx
class Iter {
        public var i : Int;
        public var e : Int;
        public inline function new(i, e) {this.i = i; this.e = e;}
        public inline function hasNext() return i < e;
        public inline function next() {var j = i; i++; return j;}
}

class Inlining2 {
        public static function main() {
                var s = 0;
                for (i in new Iter(0, 10)) {
                        s += i;
                }
        }
}
```

generated js:
```js
Inlining2.main = function() {
	var s = 0;
	var _g = new Iter(0,10);
	while(_g.i < _g.e) {
		var i = _g.next();
		s += i;
	}
};
```

```haxe
// Inlining3.hx
class Iter {
        public var i : Int;
        public var e : Int;
        var j : Int;
        public inline function new(i, e) {this.i = i; this.e = e;}
        public inline function hasNext() return i < e;
        public inline function next() {j = i; i++; return j;}
}

class Inlining3 {
        public static function main() {
                var s = 0;
                for (i in new Iter(0, 10)) {
                        s += i;
                }
        }
}
```

generated js:
```js
Inlining3.main = function() {
	var s = 0;
	var _g_j = _g_i;
	var _g_i = 0;
	var _g_e = 10;
	while(_g_i < _g_e) {
		var i;
		_g_j = _g_i;
		_g_i++;
		i = _g_j;
		s += i;
	}
};
```

**Comment by Simn** [comment]
This is probably the same as #3535.

**Comment by mandel59** [comment]
I found inlining in Inlining3 is wrong. The third line `var _g_j = _g_i;` is wired. The variable `_g_i` is not initialized in that line, so it raise an error in other platforms, including PHP.

```
uncaught exception: Undefined variable: _g_i (errno: 8) in /Users/ryama/work/prog/haxe/unifilltest/inlining3_php/lib/Inlining3.class.php at line #9Undefined variable: _g_i

in file: /Users/ryama/work/prog/haxe/unifilltest/inlining3_php/lib/Inlining3.class.php line 9
#0 /Users/ryama/work/prog/haxe/unifilltest/inlining3_php/lib/Inlining3.class.php(9): _hx_error_handler(8, 'Undefined varia...', '/Users/ryama/wo...', 9, Array)
#1 /Users/ryama/work/prog/haxe/unifilltest/inlining3_php/index.php(9): Inlining3::main()
#2 {main}%                                                                                                                                                      
```

**Comment by Simn** [comment]
You're right, there's something going wrong there.
