### ISSUE TITLE
php missing dynamic function implementation

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe#4924]
```haxe
class Test {
	function new():Void {}
	dynamic function test():String return "test";
	static function main():Void {
		new Test().test();
	}
}
```
compiles to php:
```
-php bin
-cp src
-main Test
-cmd php bin/index.php
# -debug # the issue goes away when compiling in debug mode...
```
error:
```
uncaught exception: call_user_func() expects parameter 1 to be a valid callback, no array or string given (errno: 2) in /Users/andy/Documents/workspace/TestHaxe/bin/lib/Test.class.php at line #6call_user_func() expects parameter 1 to be a valid callback, no array or string given

in file: /Users/andy/Documents/workspace/TestHaxe/bin/lib/Test.class.php line 6
#0 [internal function]: _hx_error_handler(2, 'call_user_func(...', '/Users/andy/Doc...', 6, Array)
#1 /Users/andy/Documents/workspace/TestHaxe/bin/lib/Test.class.php(6): call_user_func(NULL)
#2 /Users/andy/Documents/workspace/TestHaxe/bin/lib/Test.class.php(19): Test->test()
#3 /Users/andy/Documents/workspace/TestHaxe/bin/index.php(11): Test::main()
#4 {main}[Finished in 0.1s]
```

The issue exists in both haxe 3.2.1 and latest haxe dev branch.
Adding `-dce no` or `-D no-analyzer` doesn't help. But `-debug` somehow fixes it....

Here is the Test.class.php generated **without** `-debug`:
```php
<?php

// Generated by Haxe
class Test {
	public function __construct() {}
	public function test() { return call_user_func($this->test); }
	public $test = null;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function main() {
		_hx_deref(new Test())->test();
	}
	function __toString() { return 'Test'; }
}
```
**with** `-debug`:
```php
<?php

// Generated by Haxe
class Test {
	public function __construct() {
		if(!isset($this->test)) $this->test = array(new _hx_lambda(array(&$this), "Test_0"), 'execute');
		if(!php_Boot::$skip_constructor) {
		$GLOBALS['%s']->push("Test::new");
		$__hx__spos = $GLOBALS['%s']->length;
		$GLOBALS['%s']->pop();
	}}
	public function test() { return call_user_func($this->test); }
	public $test = null;
	public function __call($m, $a) {
		if(isset($this->$m) && is_callable($this->$m))
			return call_user_func_array($this->$m, $a);
		else if(isset($this->__dynamics[$m]) && is_callable($this->__dynamics[$m]))
			return call_user_func_array($this->__dynamics[$m], $a);
		else if('toString' == $m)
			return $this->__toString();
		else
			throw new HException('Unable to call <'.$m.'>');
	}
	static function main() {
		$GLOBALS['%s']->push("Test::main");
		$__hx__spos = $GLOBALS['%s']->length;
		_hx_deref(new Test())->test();
		$GLOBALS['%s']->pop();
	}
	function __toString() { return 'Test'; }
}
function Test_0(&$__hx__this) {
	{
		$GLOBALS['%s']->push("Test::new");
		$__hx__spos = $GLOBALS['%s']->length;
		{
			$GLOBALS['%s']->pop();
			return "test";
		}
		$GLOBALS['%s']->pop();
	}
}
```

**Comment by mockey** [comment]
I think this is same as descibed here: #4723

**Comment by andyli** [comment]
Indeed!

**Comment by mockey** [comment]
Hm, just faced that issue again as well.
A temporary workaround is adding some dce-resistant var to the constructor, like:
```
  function new():Void {
    untyped __php__("$fixme");
  }
```
