### ISSUE TITLE
[python] Cannot delete field named in python keyword

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#5016]
```haxe
class Main
{
	static function main()
	{
		var obj = {abc:null, def:1}
		Reflect.deleteField(obj, 'def');
	}
}
```

Error:
```
Traceback (most recent call last):
  File "bin/test.py", line 35, in <module>
    Main.main()
  File "bin/test.py", line 15, in main
    Reflect.deleteField(_hx_AnonObject({'abc': None, '_hx_def': 1}),"def")
  File "bin/test.py", line 25, in deleteField
    o.__delattr__(field)
AttributeError: def
```

**Comment by Simn** [comment]
Indeed, but what could be possibly do about that?

**Comment by ncannasse** [comment]
Most likely "def" is a python keyword so the field is escaped ?

**Comment by Simn** [comment]
Oh, if that's the problem then it's an easy fix.

**Comment by Simn** [comment]
Oh, the [test](https://github.com/HaxeFoundation/haxe/blob/development/tests/unit/src/unit/issues/Issue5016.hx) I added fails on hxcpp. I think this falls under the defined part of reflection.
