### ISSUE TITLE
[python] AttributeError on access of conditionally initialized member

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5053]
```haxe
class Main {
    public static function main() {
		new Main().foo();
	}

	var field:String;

	public function new() {
		if (Math.random() > 1) {
			field = "";
		}
	}

	public function foo() {
		trace(field != null);
	}
}
```

```python
# Generated by Haxe

import random as python_lib_Random


class Main:
    __slots__ = ("field",)

    def __init__(self):
        # source/Main.hx:9
        if (python_lib_Random.random() > 1):
            self.field = ""

    def foo(self):
        # source/Main.hx:15
        print(str((self.field is not None)))

    @staticmethod
    def main():
        # source/Main.hx:3
        Main().foo()




Main.main()
```

```
> python3 run.py
Traceback (most recent call last):
  File "run.py", line 26, in <module>
    Main.main()
  File "run.py", line 21, in main
    Main().foo()
  File "run.py", line 16, in foo
    print(str((self.field is not None)))
AttributeError: field

```

**Comment by nadako** [comment]
@Simn do we have some filter that follows the flow and can tell us if field is initialized or not, so we could add a `self.field = None` in case it's not always initialized. Ideally it would only add that to the false branches, but that's too complex I suppose.

**Comment by Simn** [comment]
That's very hard to detect because fields could be initialized by sub-class constructors or even some random function if they are public.

**Comment by nadako** [comment]
Oh, right. Well, for a quick fix we should bring back `self.field = None` initializations. In the long term we may look into using meta-classes for this stuff as well as reflection/type api stuff.

**Comment by nadako** [comment]
This is a regression.

**Comment by Simn** [comment]
I'll take it.
