### ISSUE TITLE
[python] AttributeError: type object 'python_internal_ArrayImpl' has no attribute '_set'

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#5059]
```haxe
class Main {
    public static function main() {
		var lines = [""];
		lines[0] += "";
		trace(lines);
	}
}
```

```
> python3 run.py
Traceback (most recent call last):
  File "run.py", line 966, in <module>
    Main.main()
  File "run.py", line 52, in main
    python_internal_ArrayImpl._set(_hx_local_0, _hx_local_1, (("null" if _hx_local_2 is None else _hx_local_2) + ""))
AttributeError: type object 'python_internal_ArrayImpl' has no attribute '_set'
```

Doesn't occur with `-dce no`.

**Comment by Gama11** [comment]
`-D dump`:

```haxe
class Main{
	static public main(method) : Void -> Void

	 = [Function:Void -> Void]
		[Block:Void]
			[Var lines(6025):list<str>] [ArrayDecl:list<str>] [Const:str] ""
			[Binop:str]
				[Array:str]
					[Local lines(6025):list<str>]
					[Const:Int] 0
				+=
				[Const:str] ""
```

**Comment by nadako** [comment]
Wow, the generated code is really ugly:
```python
    def main():
        lines = [""]
        _hx_local_0 = lines
        _hx_local_1 = 0
        _hx_local_2 = (_hx_local_0[_hx_local_1] if _hx_local_1 >= 0 and _hx_local_1 < len(_hx_local_0) else None)
        python_internal_ArrayImpl._set(_hx_local_0, _hx_local_1, (("null" if _hx_local_2 is None else _hx_local_2) + ""))
        (_hx_local_0[_hx_local_1] if _hx_local_1 >= 0 and _hx_local_1 < len(_hx_local_0) else None)
        print(str((("[" + HxOverrides.stringOrNull(",".join([python_Boot.toString1(x1,'') for x1 in lines]))) + "]")))
```
We should look into not generating extra locals when we're dealing with locals/constants already.

**Comment by nadako** [comment]
Strange, `ArrayImpl._set` is supposed to be kept when feature `array_write` is added, but it's added on `OpAssign(Op)` here: https://github.com/HaxeFoundation/haxe/blob/development/src/optimization/dce.ml#L432

**Comment by Simn** [comment]
I briefly looked at that yesterday, my only guess is that `is_array` doesn't hold for some reason because the AST structure looks sane.

**Comment by nadako** [comment]
Wait, why `lines` is typed as `list<str>`? Does dce happens after applying `@:native`?

**Comment by Simn** [comment]
No but the dump does. You should get Array if you print it in DCE, no?

**Comment by nadako** [comment]
Yeah, it prints Array...

**Comment by nadako** [comment]
Oh, I think it's related to string concat, since it seems to match this pattern instead of one related to array write:

```ocaml
| TBinop( (OpAdd | (OpAssignOp OpAdd)),e1,e2) when ((is_string e1.etype || is_string e2.etype) && not ( is_const_string e1 && is_const_string e2)) ->
```
