### ISSUE TITLE
[python] FileSystem.stat() throws AttributeError: 'os.stat_result' object has no attribute 'st_rdev'

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#5380]
Executing
```haxe
class Test {
    static function main() {
        sys.io.File.saveContent("test.txt", "hi");
        sys.FileSystem.stat("test.txt");
    }
}
```
works on all platforms except Python, where it fails with
```
Traceback (most recent call last):
  File "target\python\Test.py", line 2234, in <module>
    hx_files_Test.main()
  File "target\python\Test.py", line 1022, in main
    sys_FileSystem.stat("test.txt")
  File "target\python\Test.py", line 156, in stat
    return _hx_AnonObject({'gid': s.st_gid, 'uid': s.st_uid, 'atime': Date.fromTime(s.st_atime), 'mtime': Date.fromTime(s.st_mtime), 'ctime': Date.fromTime(s.st_ctime), 'size': s.st_size, 'dev': s.st_dev, 'ino': s.st_ino, 'nlink': s.st_nlink, 'rdev': s.st_rdev, 'mode': s.st_mode})
AttributeError: 'os.stat_result' object has no attribute 'st_rdev'
```

Tested with Haxe 3.3.0-rc1 and Python 3.5.1

Using an absolute path with `FileSystem.stat` results in the same error.

**Comment by sebthom** [comment]
Thanks!
