### ISSUE TITLE
[php7] PHP Fatal error: Uncaught Error: Class 'haxe\CallStack' not found

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#6046]
I am getting a `PHP Fatal error: Uncaught Error: Class 'haxe\CallStack' not found` error when executing the test cases of the [haxe-strings](https://github.com/vegardit/haxe-strings) library while targeting PHP7. The problem only occurs with the new PHP7 target, even when DCE is disabled.

I tried to create a small test case but could unfortunately not reproduce it. 

The generated PHP7 code contains `use \haxe\CallStack;` statements in several PHP files that were inserted by the transpiler. But a `CallStack.php` file itself is not generated.
The PHP code generated by the old transpiler does not contain any references to `haxe.CallStrack`.

The problem can be reproduced by executing the test cases via https://github.com/vegardit/haxe-strings/blob/master/test-php7.cmd

Any advice would be appreciated.

**Error:**
```
DocTestRunner.hx:51: [INFO] Invoking [hx.strings.TestRunner#testEnglishSpellChecker_1()]...                                                                                                 
hx.strings.TestRunner:1: [INFO] **********************************************************                                                                                                  
hx.strings.TestRunner:1: [INFO] Doc Testing [src/hx/strings/spelling/checker/EnglishSpellChecker.hx] #1...                                                                                  
hx.strings.TestRunner:1: [INFO] **********************************************************                                                                                                  
PHP Fatal error:  Uncaught Error: Class 'haxe\CallStack' not found in D:\haxe-projects\haxe-strings\target\php7\lib\hx\strings\TestRunner.php:10749                                         
Stack trace:                                                                                                                                                                                
#0 [internal function]: hx\strings\TestRunner->testEnglishSpellChecker_1()                                                                                                                  
#1 D:\haxe-projects\haxe-strings\target\php7\lib\php\_Boot\HxClosure.php(58): call_user_func_array(Array, Array)                                                                            
#2 D:\haxe-projects\haxe-strings\target\php7\lib\Reflect.php(32): php\_Boot\HxClosure->callWith(Object(hx\strings\TestRunner), Array)                                                       
#3 D:\haxe-projects\haxe-strings\target\php7\lib\hx\doctest\DocTestRunner.php(237): Reflect::callMethod(Object(hx\strings\TestRunner), Object(php\_Boot\HxClosure), Object(Array_hx))       
#4 D:\haxe-projects\haxe-strings\target\php7\lib\hx\doctest\DocTestRunner.php(398): hx\doctest\DocTestRunner->run(0)                                                                        
#5 D:\haxe-projects\haxe-strings\target\php7\lib\hx\strings\TestRunner.php(46): hx\doctest\DocTestRunner->runAndExit()                                                                      
#6 D:\haxe-projects\haxe-strings\target\php7\index.php(12): hx\strings\TestRunner::main()                                                                                                   
#7 {main}                                                                                                                                                                                   
  thrown in D:\haxe-projects\haxe-strings\target\php7\lib\hx\strings\TestRunner.php on line 10749                                                                                           
```

**Comment by sebthom** [comment]
Thanks for the quick fix!

**Comment by filt3rek** [comment]
Hej all,

I just had the same issue with haxe_2018-12-22_development_a22c346, I put -dce no but I get this exception when server try to return things to the client through remoting.
Any idea please ?

**Comment by RealyUniqueName** [comment]
Could you provide a reproducible sample?

**Comment by filt3rek** [comment]
Hej,
Sorry I haven't seen your answer, thanks.
You can do just that in order to get that error :

```
class Server{
	public static function main(){
		try{
			throw "foo";
		}catch ( e : Dynamic ){
			throw e;
		}
}
```

**Comment by RealyUniqueName** [comment]
@filt3rek your bug is caused by #7693

**Comment by filt3rek** [comment]
I see, thanks Alexander !
