### ISSUE TITLE
[PHP7] PHP Fatal error:  Uncaught ErrorException: Undefined index

### ISSUE THREAD

**Issue by gamedevsam** [HaxeFoundation/haxe#6161]
I'm getting this error when compiling with ```-D php7```:
```
[07-Apr-2017 03:57:39 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files (x86)\iis express\PHP\v7.1\ext\php_mysql.dll' - The specified module could not be found.
 in Unknown on line 0
[06-Apr-2017 23:57:39 America/New_York] PHP Fatal error:  Uncaught ErrorException: Undefined index: userData in C:\Users\Samuel\Dev\HTML\TradersLedger\www\lib\Main.php:23
Stack trace:
#0 C:\Users\Samuel\Dev\HTML\TradersLedger\www\lib\Main.php(23): php\Boot::php\{closure}(8, 'Undefined index...', 'C:\\Users\\Samuel...', 23, Array)
#1 C:\Users\Samuel\Dev\HTML\TradersLedger\www\lib\Main.php(24): Main::{closure}()
#2 C:\Users\Samuel\Dev\HTML\TradersLedger\www\index.php(12): Main::main()
#3 {main}
  thrown in C:\Users\Samuel\Dev\HTML\TradersLedger\www\lib\Main.php on line 23
```

This is Main.php on line 23:
```
$userData = base64_decode(((function ()  use (&$postData) {
	$this1 = $postData->data;
	return $this1["userData"];
})() ?? null));
```

The application runs fine without ```-D php7```. Any idea what's causing this?

**Comment by RealyUniqueName** [comment]
Please, provide a Haxe code to reproduce this issue.

**Comment by RealyUniqueName** [comment]
ping @gamedevsam

**Comment by gamedevsam** [comment]
I will try!

**Comment by RealyUniqueName** [comment]
Any news? :)

**Comment by RealyUniqueName** [comment]
I'm closing this due to lack of feedback. Feel free to reopen.
