### ISSUE TITLE
 haxe.Utf8.iter seems to be incosistent

### ISSUE THREAD

**Issue by romanmikhailov** [HaxeFoundation/haxe#6498]
Hi

I have an issue when try to receive utf8 bytes from multibyte character (Example below looks on euro character '€').

Native `haxe.Utf8.iter` retrieves values in Utf16.

In example before `test_nativeUtf8BytesGetter` method tests native realization. And the `test_customUtf8BytesGetter` tests custom port of google closure.

Is it correct behavior?

Haxe: 3.4.2
hxcs: 3.4.0
macOS: 10.12.6
nodejs: v8.1.2
mono: 5.0.1.1

`Main.hx`
```haxe
package;

import haxe.unit.TestCase;
import haxe.unit.TestRunner;
import haxe.Utf8;

class Main extends TestCase {
	public static function main():Void {
		var runner:TestRunner = new TestRunner();
		runner.add(new Main());
		var result = runner.run();
		#if sys
		if (!result) {
			Sys.exit(1);
		}
		#end
	}

	public function test_nativeUtf8BytesGetter() {
		var bytes:Array<Int> = [];
		Utf8.iter("€", function(code:Int):Void bytes.push(code));

		assertEquals(226, bytes[0]);
		assertEquals(130, bytes[1]);
		assertEquals(172, bytes[2]);
	}

	public function test_customUtf8BytesGetter() {
		var bytes:Array<Int> = stringToUtf8ByteArray("€");

		assertEquals(226, bytes[0]);
		assertEquals(130, bytes[1]);
		assertEquals(172, bytes[2]);
	}

	// goog.crypt.stringToUtf8ByteArray
	private function stringToUtf8ByteArray(str:String):Array<Int> {
		var out:Array<Int> = [];
		var p:Int = 0;
		var i = 0;
		while (i < str.length) {
			var c = str.charCodeAt(i);
			if (c < 128) {
				out[p++] = c;
			} else if (c < 2048) {
				out[p++] = (c >> 6) | 192;
				out[p++] = (c & 63) | 128;
			} else if (
				((c & 0xFC00) == 0xD800) && (i + 1) < str.length &&
				((str.charCodeAt(i + 1) & 0xFC00) == 0xDC00)) {
				// Surrogate Pair
				c = 0x10000 + ((c & 0x03FF) << 10) + (str.charCodeAt(++i) & 0x03FF);
				out[p++] = (c >> 18) | 240;
				out[p++] = ((c >> 12) & 63) | 128;
				out[p++] = ((c >> 6) & 63) | 128;
				out[p++] = (c & 63) | 128;
			} else {
				out[p++] = (c >> 12) | 224;
				out[p++] = ((c >> 6) & 63) | 128;
				out[p++] = (c & 63) | 128;
			}
			i++;
		}
		return out;
	}
}
```

`build_cs.hxml`
```
-cs bin/cs

-cp .
-main Main
-dce full
-debug
-D real-position

--next 

-cmd mono bin/cs/bin/Main-Debug.exe
```

`build_js.hxml`
```
-js bin/js/main.js
-cp .
-main Main
-dce full
-debug

--next

-cmd node bin/js/main.js
```

`Console output`
```
$ haxe build_js.hxml 
Class: Main F.
* Main::test_nativeUtf8BytesGetter()
ERR: Main.hx:23(Main.test_nativeUtf8BytesGetter) - expected '226' but was '8364'

Called from module Error: [object Object]
Called from module at Main.assertEquals (/bin/js/main.js:128:10)
Called from module at Main.test_nativeUtf8BytesGetter ("input": "$1",/bin/js/main.js:149:8)
Called from module at haxe_unit_TestRunner.runCase ("input": "$1",/bin/js/main.js:562:12)
Called from module at haxe_unit_TestRunner.run ("input": "$1",/bin/js/main.js:538:9)
Called from module at Function.Main.main ("input": "$1",/bin/js/main.js:140:22)
Called from module at "input": "$1",/bin/js/main.js:866:6
Called from module at Object.<anonymous> ("input": "$1",/bin/js/main.js:867:3)
Called from module at Module._compile (module.js:569:30)
Called from module at Object.Module._extensions..js (module.js:580:10)
Called from module at Module.load (module.js:503:32)


FAILED 2 tests, 1 failed, 1 success



$ haxe build_cs.hxml 
haxelib run hxcs hxcs_build.txt --haxe-version 3402 --feature-level 1
Note: dmcs is deprecated, please use mcs instead!
Class: Main F.
* Main::test_nativeUtf8BytesGetter()
ERR: Main.hx:23(Main.test_nativeUtf8BytesGetter) - expected '226' but was '8364'

Called from haxe.unit.TestCase.assertEquals (null line 0)
Called from Main.test_nativeUtf8BytesGetter (null line 0)
Called from Main.__hx_invokeField (null line 0)
Called from haxe.lang.Runtime.callField (null line 0)
Called from haxe.lang.Closure.__hx_invokeDynamic (null line 0)
Called from Reflect.callMethod (null line 0)
Called from haxe.unit.TestRunner.runCase (null line 0)


FAILED 2 tests, 1 failed, 1 success
Error: Command failed with error 1
```

**Comment by Aurel300** [comment]
What exactly is the problem? Your tests are wrong. The documentation for the `haxe.Utf8.iter` function says:

> Call the `chars` function for each UTF8 char of the string.

A UTF8 character is not a byte. The character `€` is character number 8364 in Unicode. If you'd like to convert the string into its byte representation, try `Bytes.ofString`, or iterate with `str.charCodeAt`. Here is a demonstration:

https://try.haxe.org/#861A3

**Comment by romanmikhailov** [comment]
@Aurel300 Thank you for clarification. I really incorrectly understood this API.
