### ISSUE TITLE
[python] AttributeError for a class without constructor

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7541]
```haxe
class Main {
	static function main() {
		var c = new Bar();
		trace(c.foo());
	}
}

class Bar extends Foo {
	public function new() {}
}

class Foo {
  var v:Int;
  public function foo() {
    return v == null;
  }
}
```

```
Traceback (most recent call last):
  File "bin/python/tests.py", line 43, in <module>
    Main.main()
  File "bin/python/tests.py", line 11, in main
    print(str(Bar().foo()))
  File "bin/python/tests.py", line 18, in foo
    return (self.v is None)
AttributeError: v
```

**Comment by frabbit** [comment]
hmm, should i generate an empty constructor in case no one is defined?

**Comment by kevinresol** [comment]
Well at least js did so:

```js
// Generated by Haxe 4.0.0-preview.5+7eb789f
(function () { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}var Main = function() { };
Main.main = function() {
	console.log("src/Main.hx:4:",new Bar().foo());
};
var Foo = function() { };
Foo.prototype = {
	foo: function() {
		return this.v == null;
	}
};
var Bar = function() {
};
Bar.__super__ = Foo;
Bar.prototype = $extend(Foo.prototype,{
});
Main.main();
})();

```
