### ISSUE TITLE
[python] crash when accessing non-existent field in anonymous object

### ISSUE THREAD

**Issue by kevinresol** [HaxeFoundation/haxe#7546]
```haxe
class Main  {
	static function main() {
		var data = haxe.Json.parse('{}');
		trace(data.field == null);
	}
}
```

Fails with

```
Traceback (most recent call last):
  File "bin/python/tests.py", line 115, in <module>
    Main.main()
  File "bin/python/tests.py", line 19, in main
    print(str((python_lib_Json.loads("{}",**python__KwArgs_KwArgs_Impl_.fromT(_hx_AnonObject({'object_hook': python_Lib.dictToAnon}))).field is None)))
AttributeError: '_hx_AnonObject' object has no attribute 'field'
```

**Comment by frabbit** [comment]
Does this work on all other targets?

**Comment by kevinresol** [comment]
Yes

**Comment by frabbit** [comment]
@Simn @ncannasse  should every field access on dynamic be safe like this, do we have unit tests for this?

**Comment by ncannasse** [comment]
Yes accessing to "missing" fields should be null as long as the object is a proper object.

**Comment by fondation451** [comment]
If we force the type of the variable `data` to be dynamic, it works fine on the python platform.

```haxe
class Main  {
	static function main() {
		var data:Dynamic = haxe.Json.parse('{}');
		trace(data.field == null);
	}
}
```
I had a look on the type of the var data. It seems that without specifying that it is dynamic, it is typed as TAnon an anonymous structure and not as TDynamic.

**Comment by RealyUniqueName** [comment]
Only happens if inferring type from `Dynamic`:
```haxe
class Main {
	static function main() {

		var instance:Dynamic = {};
		trace(instance.field); //ok

		trace(({}:Dynamic).timeout); //ok

		var instance = ({}:Dynamic);
		trace(instance.field); //runtime error
	}
}
```
