### ISSUE TITLE
Possible PHP7 haxe.Serializer bug

### ISSUE THREAD

**Issue by filt3rek** [HaxeFoundation/haxe#8016]
Hej all,

I'm sorry it's the minimalest example I was able to write, I'm on this strange bug for few days now.
It gives me a weired PHP fatal error (What I understand is that it's looking for a static field named "xfields" while it's a member one) :

```
Fatal error: Uncaught ErrorException: Undefined property: Tag::$xfields in /srv/www/aioli/test/lib/Object_hx.php:50

Stack trace: 
#0 /srv/www/aioli/test/lib/Object_hx.php(50): php\Boot::php\{closure}(8, 'Undefined prope...', '/srv/www/aioli/...', 50, Array)
#1 /srv/www/aioli/test/lib/Object_hx.php(65): Object_hx->get_xfields()
#2 /srv/www/aioli/test/lib/Tag.php(46): Object_hx->hxSerialize(Object(haxe\Serializer))
#3 /srv/www/aioli/test/lib/haxe/Serializer.php(495): Tag->hxSerialize(Object(haxe\Serializer))
#4 /srv/www/aioli/test/lib/haxe/Serializer.php(361): haxe\Serializer->serialize(Object(Tag))
#5 /srv/www/aioli/test/lib/haxe/Serializer.php(107): haxe\Serializer->serialize(Object(haxe\ds\StringMap))
#6 /srv/www/aioli/test/lib/Main.php(39): haxe\Serializer::run(Object(haxe\ds\StringMap))
#7 /srv/www/aioli/test/index.php(14): Main::main()
#8 {main} thrown in /srv/www/aioli/test/lib/Object_hx.php on line 50
```
I've attached a zip where you have the source, the build and the sql file, all to check quickly if you want.
[src.zip](https://github.com/HaxeFoundation/haxe/files/2983801/src.zip)

My file is : 
```haxe
import haxe.Serializer;
import haxe.Unserializer;
import haxe.ds.StringMap;

import sys.db.Manager;
import sys.db.Mysql;
import sys.db.Types;

class Object extends sys.db.Object{
	
	public var id	: SId;
	
	@:skip
	public var xfields	(get, null)	: Array<String>;
	
	function get_xfields(){
		if ( xfields == null )	xfields	= [ "id" ];
		return xfields;
	}
	
	function hxSerialize( s : Serializer ){
		s.serialize( xfields.join( "," ) );
		for ( xfield in xfields ){
			var v	= Reflect.getProperty( this, xfield );
			s.serialize( v );
		}
	}
	
	function hxUnserialize( u : Unserializer ){
		xfields		= u.unserialize().split( "," );
		for ( xfield in xfields ){
			Reflect.setProperty( this, xfield, u.unserialize() );
		}
	}
	
	public function new(){
		super();
	}
	
}

@:table( "tag_assignment" )
class TagAssignment extends Object{
	@:relation( tagID )
	public var tag		: SNull<Tag>;
	@:relation( contactID )
	public var contact	: SNull<Contact>;
}

@:table( "tag" )
class Tag extends Object{
	public var name	: SString<255>; 
	
	override function hxSerialize( s : Serializer ){
		super.hxSerialize( s );
		
		s.serialize( name );
	}
	
	override function hxUnserialize( u : Unserializer ){
		super.hxUnserialize( u );
		
		name	= u.unserialize();
	}
	
	public function new(){
		super();
	}
}

@:table( "contact" )
class Contact extends Object{
	public var name	: SString<255>; 
	public var fname	: SString<255>; 
	
	@:skip
	public var tags		(get, null)	: StringMap<Tag>;
	
	function get_tags(){
		var tas	= TagAssignment.manager.search( $contactID == id );
		var h	= new StringMap();
		for ( ta in tas ){
			h.set( ta.tag.name, ta.tag );
		}
		return h;
	}
	
	override function hxSerialize( s : Serializer ){
		super.hxSerialize( s );
		
		s.serialize( name );
		s.serialize( fname );
		s.serialize( tags );
	}
	
	override function hxUnserialize( u : Unserializer ){
		super.hxUnserialize( u );
		
		name	= u.unserialize();
		fname	= u.unserialize();
		tags	        = u.unserialize();
	}
	
	public function new() {
		super();
	}
}

class Main {

	static function main() {
		Serializer.USE_CACHE	= true;
		
		Manager.cnx	= Mysql.connect( { host	: "localhost", user : "root", pass : "", database : "test" } );
		Manager.cnx.request( "SET NAMES utf8" );
		Manager.initialize();
		Manager.cleanup();
		
		var contact	= Contact.manager.get( 1 );
			
		Serializer.run( contact );       // <----- If commented, all works fine
		
		var tags	= Tag.manager.all();  // <----- If commented, all works fine too
		
		Serializer.run( contact.tags );
	}
}
```
As you can see, if I comment the first serialization or just the query to get all tags, there are no error.

**Comment by filt3rek** [comment]
Maybe it could be linked to this issue that I've closed : https://github.com/HaxeFoundation/haxe/issues/7635 but maybe I shouldn't because these issues don't occur on neko target for example...

**Comment by filt3rek** [comment]
I don't know if it can help but if I cleanup the SPOD cache between, it works fine : 
```haxe
var contact	= Contact.manager.get( 1 );
Serializer.run( contact );
Manager.cleanup();  // <--------- !!!
var tags	= Tag.manager.all();
Serializer.run( contact.tags );
```

**Comment by filt3rek** [comment]
It seems the getter `get_xfields`is called twice everytime, maybe something here ?

**Comment by RealyUniqueName** [comment]
Which versions of Haxe and SPOD library are you using?

**Comment by RealyUniqueName** [comment]
It's a bug in record-macros. The field gets deleted here: https://github.com/HaxeFoundation/record-macros/blob/f32f71a7f45d346fd19d2af923b972461c5ccf33/src/sys/db/Manager.hx#L673
Please submit an issue to record-macros repo.

**Comment by filt3rek** [comment]
Hej Alexander,

Thanks for your answer. I've commented the line you said and it works. Clearing cache does work too as I said. But why does it work on Neko without any error ?
And why does PHP throw a weired error like that ? What has "xfields" to do with that please ?

**Comment by filt3rek** [comment]
Alexander,

I've even tried with PHP 5 (the old Haxe/PHP) target, and it works fine that's why I think it could be a PHP7 bug.

**Comment by filt3rek** [comment]
Hmm I think you're right Alexander.
In Neko and PHP5 it doesn't throw any error until I added traces in the loop where it deletes all the class fileds, and not only the ones used in the DB : https://github.com/HaxeFoundation/record-macros/issues/34
Sorry for my misunderstanding...
