### ISSUE TITLE
[python] Runtime error upon accessing non-existent field of anonymous object inferred from Dynamic

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8105]
```haxe
class Main {
	static function main() {

		var instance:Dynamic = {};
		trace(instance.field); //ok

		trace(({}:Dynamic).timeout); //ok

		var instance = ({}:Dynamic);
		trace(instance.field); //runtime error
	}
}
```
```
$ haxe -main Main -python test.py && python3 test.py
None
None
Traceback (most recent call last):
  File "bin/test.py", line 741, in <module>
    Main.main()
  File "bin/test.py", line 46, in main
    print(str(_hx_AnonObject({}).field))
AttributeError: '_hx_AnonObject' object has no attribute 'field'
```

**Comment by Gama11** [comment]
Same as https://github.com/HaxeFoundation/haxe/issues/5051?

**Comment by RealyUniqueName** [comment]
Duplicates #7546

**Comment by RealyUniqueName** [comment]
> Same as #5051?

No. That one was about properly typed var. This one is about inerred `Dynamic`.
