### ISSUE TITLE
[jvm] haxe.extern.Rest doesn't seem to work

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe#8272]
```haxe
class Main {
	static function main() {
		trace(java.NativeString.format("%d %.2f", 1, 1.2556));
	}
}
```

Works with the Java target, but not JVM, where this happens:

```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Main.main([Ljava/lang/String;)V @18: invokestatic
  Reason:
    Type 'java/lang/Integer' (current frame, stack[5]) is not assignable to 'Array'
  Current Frame:
    bci: @18
    flags: { }
    locals: { '[Ljava/lang/String;' }
    stack: { 'java/lang/invoke/MethodHandle', '[Ljava/lang/Object;', '[Ljava/lang/Object;', integer, 'java/lang/String', 'java/lang/Integer', double, double_2nd }
  Bytecode:
    0x0000000: b200 0a05 bd00 0c59 0312 0e04 b800 1414
    0x0000010: 0015 b800 1c53 5904 bb00 1e59 121f 1221
    0x0000020: 0612 23b7 0027 53b8 002d 57b1

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main"
```

**Comment by nadako** [comment]
I actually wonder why `Rest<T>` is an abstract over `Array<T>` instead of some `@:coreType` abstract?

**Comment by Simn** [comment]
We have to check what real Java generates here. I don't really understand how many stack elements are consumed as arguments.

**Comment by Simn** [comment]
Oh I guess it just creates an implicit array...
