### ISSUE TITLE
[python] Sys.stdin().readLine() fails on Unicode input

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe#8373]
```haxe
class Main {
  public static function main():Void Sys.stdin().readLine();
}
```

```bash
$ haxe --main Main --python out.py
$ echo "č" | python3 out.py
Traceback (most recent call last):
  File "out.py", line 580, in <module>
    Main.main()
  File "out.py", line 37, in main
    Sys.stdin().readLine()
  File "out.py", line 569, in readLine
    return self.impl.readLine()
  File "out.py", line 153, in readLine
    raise _hx_e
  File "out.py", line 142, in readLine
    s = buf.getBytes().toString()
  File "out.py", line 81, in getBytes
    buf = bytearray(self.b)
ValueError: byte must be in range(0, 256)
```

**Comment by Aurel300** [comment]
https://github.com/HaxeFoundation/haxe/blob/e99098cdc07d29b7945949bcf759e7d60480ab06/std/python/io/NativeTextInput.hx#L44-L48
