### ISSUE TITLE
[jvm] VerifyError in a specific pattern matching

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe#8491]
on Java with `-D jvm` and `-D analyzer-optimize`, the following code

```haxe
class C {}

enum E {
	A(v:C);
}

class Main {
	static final ident:C = null;

	static function f(e:E):Int {
		return switch e {
			case A(ident): 0;
		}
	}

	static function main() {}
}
```

gives a run-time error

```
java.lang.VerifyError: Method expects a return value
Exception Details:
  Location:
    Main.f(LE;)I @17: return
  Reason:
    Error exists in the bytecode
  Bytecode:
    0x0000000: 2ac0 0007 b400 0a4c 2bb2 000d a600 0503
    0x0000010: acb1
  Stackmap Table:
    append_frame(@17,Object[#15])

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```

the AST looks like this:

```
static function f[Function:(e : E) -> Int]
	[Arg:E] [Local e(141090):E]
	[Block:Void]
		[Switch:Void]
			[Parenthesis:C]
				[EnumParameter:C]
					[Local e(141090):E:E]
					A
					0
			[Case:Dynamic]
				[Field:C]
				[TypeExpr Main:{ Statics Main }]
				[FStatic:C]
					Main
					ident:C
				[Return:Dynamic] [Const:Int] 0
```

this suggests that it tried to use the `indent` constant to match against, instead of a capture var, which is I guess is fair enough, but then the match is not exhaustive, so it should fail at Haxe compilation, right?

**Comment by nadako** [comment]
Probably a duplicate of #8277?

**Comment by Simn** [comment]
It is indeed.
