### ISSUE TITLE
[python] Bit shift by a negative number throws

### ISSUE THREAD

**Issue by RealyUniqueName** [HaxeFoundation/haxe#8844]
```haxe
class Main {
    public static function main() {
        trace(Std.random(100) << -1);
    }
}
```
At runtime:
```
$ python3 bin/test.py 
Traceback (most recent call last):
  File "bin/test.py", line 36, in <module>
    Main.main()
  File "bin/test.py", line 20, in main
    print(str((int((python_lib_Random.random() * 100)) << -1)))
ValueError: negative shift count
```
Other targets work without exceptions.

Is negative shift specified?

**Comment by RealyUniqueName** [comment]
As said by @ncannasse on slack :
> Negative and over 32 are unspecified
