### ISSUE TITLE
[python] Throwing an instance of (or from) an `Exception` class throws a TypeError.

### ISSUE THREAD

**Issue by Marika-0** [HaxeFoundation/haxe#9128]
Throwing an instance of a class `Exception`, or throwing an exception from a class `Exception`, throws a TypeError exception. Catching a thrown instance of a class `Exception`, or catching an exception thrown from a class `Exception`, throws another TypeError exception.

```haxe
class Main {
    static function main() {
        try {
            throw new Exception();
        } catch (ex:Dynamic) {}
    }
}

class Exception {
    public function new() {}
}
```

When compiling the above in `Main.hx` with `haxe --main Main --python run.py` and running with `python3 run.py`, this happens:

```
Traceback (most recent call last):
  File "run.py", line 13, in main
    raise _HxException(Exception())
  File "run.py", line 65, in __init__
    super().__init__(message)
TypeError: __init__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 83, in <module>
    Main.main()
  File "run.py", line 14, in main
    except Exception as _hx_e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

Tested with "haxe_2020-02-05_development_e686af4" using Python 3.7.5.

Here's the compiled `run.py` file, but with a txt extension so that GitHub will accept it: [run.txt](https://github.com/HaxeFoundation/haxe/files/4173803/run.txt).

The same issue occurs if throwing an exception from the `Exception` class like so:
```haxe
class Main {
    static function main() {
        try {
            new Exception();
        } catch (ex:Dynamic) {}
    }
}

class Exception {
    public function new() {
        throw("Hello, World!");
    }
}
```

If I had to guess I'd say that Python doesn't like a class `"Exception"` existing, because this doesn't happen if I rename `Exception` to `MyException`.

**Comment by RealyUniqueName** [comment]
This happens because at run time there is a [native python `Exception` class](https://docs.python.org/3/library/exceptions.html#Exception)
By defining a custom `Exception` class in the root package you override native `Exception`.
Haxe's exception implementation for python target uses native `Exception`, which gets overridden by the custom one. Hence the errors.
Similar situation could happen with other targets too.

I'm not sure what would be the best solution here.
I can see a solution in doing two things:
- provide an ability to generate all Haxe types of root package into some prefix-package (like `-D php-prefix=mypack` flag for php);
- emit compilation errors from target generators if a non-extern type has the same package+name as the native one.

**Comment by Gama11** [comment]
Isn't this a bit like using an identifier name that's a reserved keyword in the target language? Those are auto-escaped, maybe something similar should be done here? (automatically move it to a `_hx_` package or similar?)

**Comment by RealyUniqueName** [comment]
I agree. That is better.
Still implementing a prefix flag would be a good addition to provide more control over target code generation.
