### ISSUE TITLE
[jvm] java.lang.VerifyError: Instruction type does not match stack map

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe#9332]
The following tests works fine on all targets, including Java, but fails for the jvm target. 

```haxe
class Test {

   public static function foo(?bar:Int = 0) {
      if (bar > 10) {
         bar--;
      }
   }

   public static function main() {
      foo();
   }
}
```

Results in:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Instruction type does not match stack map
Exception Details:
  Location:
    Test.foo(Ljava/lang/Integer;)V @44: return
  Reason:
    Type 'java/lang/Object' (current frame, locals[1]) is not assignable to 'java/lang/Integer' (stack map, locals[1])
  Current Frame:
    bci: @44
    flags: { }
    locals: { 'java/lang/Integer', 'java/lang/Object' }
    stack: { }
  Stackmap Frame:
    bci: @44
    flags: { }
    locals: { 'java/lang/Integer', 'java/lang/Integer' }
    stack: { }
  Bytecode:
    0x0000000: 2ac7 000a 03b8 000a a700 042a 4c2b 59c7
    0x0000010: 0008 5703 a700 10b6 0010 100a a400 0704
    0x0000020: a700 0403 9900 082b b800 164c b1
  Stackmap Table:
    same_frame(@11)
    same_locals_1_stack_item_frame(@12,Object[#6])
    full_frame(@23,{Object[#6],Object[#6]},{Object[#6]})
    same_frame(@35)
    same_locals_1_stack_item_frame(@36,Integer)
    same_frame(@44)

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
```

I can make it work on jvm by changing `foo(?bar:Int = 0)` to `foo(bar:Int = 0)`

**Comment by Simn** [comment]
Please see if that reproduces with a nightly build. From a quick check it doesn't reproduce for me on latest Haxe.

**Comment by sebthom** [comment]
Yes, seems to be fixed in nightly. Thanks!
