### ISSUE TITLE
[java/jvm]not support sqlite.

### ISSUE THREAD

**Issue by sonygod** [HaxeFoundation/haxe#9429]
```haxe
class Main {
	static function main() {
		var cnx = sys.db.Sqlite.open("./backup.data");
		trace('create table now');
		cnx.request("
				CREATE TABLE IF NOT EXISTS fa_customer (
				id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
				
				nickname text(255)
				
				
				
				)");

		trace('create table finish');

		var sql = 'INSERT INTO fa_customer (nickname) VALUES (${cnx.quote("豪鬼")})';
		trace(sql);
		cnx.request(sql);

		trace("sqlite init finish");
	}
}
```

```
/usr/local/share/haxe/std/java/db/Jdbc.hx:269: characters 14-22 : [Ident:java.lang.String -> Unknown<0>] __java__
```

**Comment by Simn** [comment]
Yes `__java__` won't work on the JVM target, so this has to be changed to actual Haxe code.

**Comment by nadako** [comment]
FWIW this example works for me, but there's indeed a wild `untyped __java__` that needs to be changed.

**Comment by sonygod** [comment]
Exception in thread "main" org.sqlite.JDBC
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at sys.db.Sqlite.open(C:\HaxeToolkit\haxe\std/java/_std/sys/db/Sqlite.hx:31)
        at haxe.root.Main.main(src/Main.hx:3)
        at haxe.root.Main.main(src/Main.hx:1)
